# Site
name: "Remote Roast"
title: "Remote Roast"
description: "Rating Twin Cities coffee shops for remote work."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
# google_analytics: 'UA-46278016-1'
disqus: 'remote-roast'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  juliet + osmar:
      name: Juliet + Osmar
      display_name: Juliet + Osmar
      avatar: 'assets/images/josmar.png' 
      email: remoteroasters@gmail.com
      description: "After four years as a barista at a Minnesota coffee chain that shall not be named, Juliet is now a Data Analyst at the Star Tribune. 
      After dropping out of bartending school, Osmar is now a computational neuroscience researcher at the University of Minnesota. They both like americanos, but Osmar prefers iced and Juliet likes it hot ;)"
  juliet:
    name: Juliet
    display_name: Juliet
    avatar: 'assets/images/juliet.jpeg' 
    email: remoteroasters@gmail.com
    description: "After four years as a barista at a Minnesota coffee chain that shall not be named, Juliet is now a Data Analyst at the Star Tribune. 
    Her favorite espresso drink is a hot americano with not too much water, but she also loves a plain old coffee or a fun flavored latte every once in a while."
  osmar:
    name: Osmar
    display_name: Osmar    
    avatar: 'assets/images/osmar.png'
    email: remoteroasters@gmail.com
    description: "After dropping out of bartending school, Osmar is now a computational neuroscience researcher at the University of Minnesota. 
    His favorite espresso drink is an iced vanilla americano (light ice), and he's also a big fan of iced chai and london fog lattes."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
